cv_project2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
     # 아래의 URL을 opencv_webapp/urls.py가 handling
    path('', include('opencv_webapp.urls')),
]

opencv_webapp/urls.py
from django.urls import path
from . import views # 같은 폴더 내의 views.py를 import
from django.conf import settings
from django.conf.urls.static import static

app_name = 'opencv_webapp'

urlpatterns = [
    path('', views.first_view, name='first_view'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('detect_face/', views.detect_face, name='detect_face'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opencv_webapp/models.py
from django.db import models

# Create your models here.
class ImageUploadModel(models.Model):
    # blank=True : Form에서 빈 채로 저장되는 것을 허용(form.is_valid)
    description = models.CharField(max_length=255, blank=True)
    document = models.ImageField(upload_to='images/%Y/%m/%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)

opencv_webapp/forms.py
from django import forms
from .models import ImageUploadModel

class UploadImageForm(forms.Form):
    title = forms.CharField(max_length=50)
    # file = forms.FileField()
    image = forms.ImageField()

class ImageUploadForm(forms.ModelForm):
    # 이 Form을 만들기 위해 ImageUploadModel을 쓰라고 알려주기 위한 내부 구현
    class Meta:
        model = ImageUploadModel
        # Form을 통해 받고자 하는 Model Class의 field 리스트
        fields = ('description', 'document', )

opencv_webapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import UploadImageForm
from django.core.files.storage import FileSystemStorage
from .forms import ImageUploadForm
from django.conf import settings
from .cv_functions import cv_detect_face

# Create your views here.
def first_view(request):
    return render(request, 'opencv_webapp/first_view.html', {})

def upload_image(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            myfile = request.FILES['image']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            context = {'form': form, 'uploaded_file_url': uploaded_file_url}
            return render(request, 'opencv_webapp/upload_image.html', context)
    else: # request.method == 'GET'
        form = UploadImageForm()
        context = {'form': form}
        return render(request, 'opencv_webapp/upload_image.html', context)

def detect_face(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False) # DB에 실제로 저장하기 전에 추가로 Form(post)에 다른 데이터 추가 가능
            post.save() # DB에 실제로 Form에 모아진 데이터를 저장

            imageURL = settings.MEDIA_URL + form.instance.document.name
            cv_detect_face(settings.MEDIA_ROOT_URL + imageURL) # 추후 구현 예정

            return render(request, 'opencv_webapp/detect_face.html', {'form':form, 'post':post})
            # post는 save() 후 DB에 저장된 ImageUploadModel 클래스 객체 자체를 갖고 있게 됨 (값이 있음 == True)
    else:
         form = ImageUploadForm()
    return render(request, 'opencv_webapp/detect_face.html', {'form':form})

opencv_webapp/templates/opencv_webapp/detect_face.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>

    <!-- image upload start-->
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>

    {% if post %}
      <!-- post.document == Model Class ImageUploadModel의 document에 해당  -->
      <img src="{{ post.document.url }}">
      <p>Uploaded file @ : <a href="{{ post.document.url }}">{{ post.document }}</a></p>
    {% endif %}

    <p><a href="{% url 'opencv_webapp:detect_face' %}">Return to home</a></p>
    <!-- image upload end -->

  </body>
</html>

opencv_webapp/templates/opencv_webapp/first_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>
    Hello world!
  </body>
</html>

opencv_webapp/templates/opencv_webapp/upload_image.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>
    <h1>Upload your image file.</h1>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" value="upload">Upload</button>
    </form>

    {% if uploaded_file_url %}
      <img src="{{ uploaded_file_url }}">
      <p>Uploaded file @ : <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

    <p><a href="{% url 'opencv_webapp:upload_image' %}">Return to home</a></p>
  </body>
</html>